// Professional Job Categories - Sorted Alphabetically
export const JOB_CATEGORIES = [
  "Academic",
  "Accounting",
  "Administration",
  "Agriculture",
  "Architecture",
  "Arts and Design",
  "Automotive",
  "Aviation",
  "Banking",
  "Business",
  "Community and Social Services",
  "Computer and IT",
  "Construction",
  "Consultancy",
  "Customer Service",
  "Education",
  "Energy and Utilities",
  "Engineering",
  "Environmental",
  "Finance",
  "Food Sciences",
  "Geology",
  "Healthcare",
  "Hospitality and Tourism",
  "Human Resource",
  "Journalism and Media",
  "Law",
  "Logistics",
  "Management",
  "Manufacturing and Industrial",
  "Marketing and Sales",
  "Mechanical Engineering",
  "Medicine",
  "Mining",
  "NGO and International Development",
  "Pharmacy",
  "Procurement",
  "Project Management",
  "Psychology",
  "Public Health",
  "Real Estate",
  "Research",
  "Security",
  "Statistics",
  "Telecommunications",
  "Other"
] as const;

// Type definition for categories
export type JobCategory = typeof JOB_CATEGORIES[number];
